CATEGORIES_DATA = [
    ("Rent", "expense", "Fixed", 15000),
    ("Electricity", "expense", "Fixed", 3000),
    ("Gas", "expense", "Fixed", 1500),
    ("Subscriptions", "expense", "Fixed", 2000),
    ("Phone & Wifi", "expense", "Fixed", 1500),
    ("Rent Insurance", "expense", "Fixed", 800),
    ("Health Insurance", "expense", "Fixed", 2500),
    ("Groceries", "expense", "Essential", 12000),
    ("Household", "expense", "Essential", 3000),
    ("Transportation", "expense", "Essential", 4000),
    ("Medical", "expense", "Essential", 2000),
    ("Eating Out", "expense", "Lifestyle", 5000),
    ("Social Events", "expense", "Lifestyle", 3000),
    ("Hobbies", "expense", "Lifestyle", 2000),
    ("Shopping", "expense", "Sinking", 5000),
    ("Beauty", "expense", "Sinking", 2000),
    ("Travel", "expense", "Sinking", 8000),
    ("Others", "expense", "Sinking", 2000),
    ("Tuition", "expense", "School", 25000),
    ("School Supplies", "expense", "School", 2000),
    ("Salary", "income", "Income", 0),
    ("Cashback", "income", "Income", 0),
    ("Interest", "income", "Income", 0),
    ("Others", "income", "Income", 0),
    ("Transfer Fees", "expense", "Misc", 0),
]
